export type Category = {
  id: string
  name: string
  description: string
  image: string
  count: number
}

export type Product = {
  id: string
  name: string
  sku: string
  category: string
  categoryId: string
  price: number
  moq: number
  unit: string
  image: string
  images: string[]
  shortDescription: string
  description: string
  specifications: { label: string; value: string }[]
  shipping: string
  leadTime: string
  inStock: boolean
  featured: boolean
  badge?: string
}

export const categories: Category[] = [
  {
    id: 'specialty',
    name: 'Specialty Foods',
    description: 'Gourmet syrups, seasonings, spice blends, and specialty condiments',
    image: '/images/category-specialty.png',
    count: 13,
  },
  {
    id: 'grocery',
    name: 'Grocery & Non-Perishables',
    description: 'Pantry staples, shelf-stable goods, and everyday grocery items',
    image: '/images/category-grocery.png',
    count: 2,
  },
  {
    id: 'wellness',
    name: 'Health & Wellness',
    description: 'Protein bars, functional foods, and wellness products',
    image: '/images/category-wellness.png',
    count: 4,
  },
  {
    id: 'home',
    name: 'Home Goods',
    description: 'Air purifier filters, home safety, and commercial storage',
    image: '/images/category-home.png',
    count: 3,
  },
  {
    id: 'kitchen',
    name: 'Kitchen & Dining',
    description: 'Food storage, wine accessories, and dining essentials',
    image: '/images/category-kitchen.png',
    count: 3,
  },
]

export const products: Product[] = [
  // ---------------- Specialty Foods ----------------
  {
    id: 'torani-vanilla-syrup',
    name: 'Torani Vanilla Syrup',
    sku: 'ETD-SPEC-1001',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 47.96,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-vanilla.jpg',
    images: ['/images/products/torani-vanilla.jpg'],
    shortDescription: 'Classic vanilla flavoring syrup for cafés, coffee shops, and foodservice, sold by the case.',
    description:
      'A café staple, Torani Vanilla Syrup delivers smooth, sweet vanilla flavor to lattes, cold brew, sodas, and desserts. A dependable high-turn item for coffee shops, restaurants, and foodservice buyers, sourced through trusted supplier relationships for consistent supply.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Price per Unit', value: '$11.99' },
      { label: 'Price per Case', value: '$47.96' },
      { label: 'Flavor', value: 'Vanilla' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 'torani-sugar-free-vanilla-syrup',
    name: 'Torani Sugar Free Vanilla Syrup',
    sku: 'ETD-SPEC-1002',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 50.0,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-sf-vanilla.png',
    images: ['/images/products/torani-sf-vanilla.png'],
    shortDescription: 'Sugar-free vanilla flavoring syrup for cafés and foodservice seeking low-calorie options.',
    description:
      'Torani Sugar Free Vanilla Syrup offers the same smooth vanilla flavor with zero sugar, sweetened for guests looking for lighter options. A strong complement to any café syrup lineup with reliable, consistent supply.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Flavor', value: 'Vanilla (Sugar Free)' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'torani-caramel-syrup',
    name: 'Torani Caramel Syrup',
    sku: 'ETD-SPEC-1003',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 48.0,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-caramel.png',
    images: ['/images/products/torani-caramel.png'],
    shortDescription: 'Rich caramel flavoring syrup for lattes, desserts, and specialty beverages.',
    description:
      'Torani Caramel Syrup brings buttery, rich caramel flavor to hot and iced beverages, desserts, and specialty drinks. A popular choice across coffee shops and foodservice, backed by dependable sourcing.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Flavor', value: 'Caramel' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'torani-hazelnut-syrup',
    name: 'Torani Hazelnut Syrup',
    sku: 'ETD-SPEC-1004',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 48.0,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-hazelnut.png',
    images: ['/images/products/torani-hazelnut.png'],
    shortDescription: 'Warm, nutty hazelnut flavoring syrup for coffee, cocoa, and specialty drinks.',
    description:
      'Torani Hazelnut Syrup adds a warm, toasted-nut sweetness that pairs perfectly with coffee and cocoa. A dependable menu builder for cafés and foodservice operators seeking consistent quality.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Flavor', value: 'Hazelnut' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'torani-french-vanilla-syrup',
    name: 'Torani French Vanilla Syrup',
    sku: 'ETD-SPEC-1005',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 48.0,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-french-vanilla.png',
    images: ['/images/products/torani-french-vanilla.png'],
    shortDescription: 'Creamy French vanilla flavoring syrup for lattes, cold brew, and desserts.',
    description:
      'Torani French Vanilla Syrup delivers a rich, custard-like vanilla flavor that rounds out any beverage program. A reliable, high-velocity flavor for coffee shops and foodservice buyers.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Flavor', value: 'French Vanilla' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'mccormick-curry-powder',
    name: 'McCormick Curry Powder',
    sku: 'ETD-SPEC-1006',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-curry.png',
    images: ['/images/products/mccormick-curry.png'],
    shortDescription: 'Golden curry powder blend for grocery, specialty, and foodservice channels.',
    description:
      'McCormick Curry Powder is a balanced blend of warm spices that adds golden color and rich flavor to countless dishes. A dependable pantry seasoning for grocery retailers and kitchens alike.',
    specifications: [
      { label: 'Container', value: 'Foodservice / retail size' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Curry Powder Blend' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'mccormick-italian-seasoning',
    name: 'McCormick Italian Seasoning',
    sku: 'ETD-SPEC-1007',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-italian.png',
    images: ['/images/products/mccormick-italian.png'],
    shortDescription: 'Classic Italian herb seasoning blend for retail and foodservice buyers.',
    description:
      'McCormick Italian Seasoning combines oregano, basil, thyme, and rosemary into a versatile, high-turn herb blend. A pantry essential across grocery and specialty food channels.',
    specifications: [
      { label: 'Container', value: 'Foodservice / retail size' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Italian Herb Blend' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 'mccormick-chili-powder',
    name: 'McCormick Chili Powder',
    sku: 'ETD-SPEC-1008',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-chili.png',
    images: ['/images/products/mccormick-chili.png'],
    shortDescription: 'Rich, warm chili powder blend for grocery and foodservice channels.',
    description:
      'McCormick Chili Powder delivers deep, warm flavor for chilis, sauces, rubs, and marinades. A dependable everyday seasoning with reliable supply for retailers and kitchens.',
    specifications: [
      { label: 'Container', value: 'Foodservice / retail size' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Chili Powder Blend' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'mccormick-garlic-powder',
    name: 'McCormick Garlic Powder',
    sku: 'ETD-SPEC-1009',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-garlic.png',
    images: ['/images/products/mccormick-garlic.png'],
    shortDescription: 'Versatile garlic powder for everyday cooking, retail, and foodservice.',
    description:
      'McCormick Garlic Powder brings convenient, consistent garlic flavor to any dish. A top-selling pantry staple with dependable supply for grocery and foodservice buyers.',
    specifications: [
      { label: 'Container', value: 'Foodservice / retail size' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Garlic Powder' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'mccormick-ground-cinnamon',
    name: 'McCormick Ground Cinnamon',
    sku: 'ETD-SPEC-1010',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-cinnamon.png',
    images: ['/images/products/mccormick-cinnamon.png'],
    shortDescription: 'Warm ground cinnamon for baking, beverages, and everyday cooking.',
    description:
      'McCormick Ground Cinnamon adds warm, sweet spice to baked goods, beverages, and breakfast favorites. A reliable, high-turn baking staple for grocery and specialty retailers.',
    specifications: [
      { label: 'Container', value: 'Foodservice / retail size' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Ground Cinnamon' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'old-bay-seasoning',
    name: 'Old Bay Seasoning',
    sku: 'ETD-SPEC-1011',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 42.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/oldbay.png',
    images: ['/images/products/oldbay.png'],
    shortDescription: 'Iconic seafood and all-purpose seasoning blend for retail and foodservice.',
    description:
      'Old Bay Seasoning is the iconic blend of herbs and spices loved on seafood, fries, snacks, and more. A recognizable, high-demand seasoning that performs across grocery and foodservice channels.',
    specifications: [
      { label: 'Container', value: 'Foodservice / retail size' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Seafood Seasoning Blend' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'Popular',
  },
  {
    id: 'zabs-hot-sauce',
    name: 'Zabs Hot Sauce',
    sku: 'ETD-SPEC-1012',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 40.0,
    moq: 12,
    unit: 'case',
    image: '/images/products/zabs-hotsauce.png',
    images: ['/images/products/zabs-hotsauce.png'],
    shortDescription: 'Bold, small-batch hot sauce for specialty food and gourmet retail.',
    description:
      'Zabs Hot Sauce delivers bold, vibrant heat and flavor for specialty food and gourmet retail channels. A distinctive condiment that adds variety to any hot sauce set, sourced through trusted supplier relationships.',
    specifications: [
      { label: 'Bottle Size', value: '5 oz' },
      { label: 'Bottles per Case', value: '12' },
      { label: 'Type', value: 'Hot Sauce' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–12 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'spicewalla-spice-blends',
    name: 'Spicewalla Spice Blends',
    sku: 'ETD-SPEC-1013',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 54.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/spicewalla.png',
    images: ['/images/products/spicewalla.png'],
    shortDescription: 'Premium small-batch spice blends in resealable tins for gourmet retail.',
    description:
      'Spicewalla Spice Blends offer fresh, small-batch spices and seasoning blends packaged in sleek resealable tins. A high-margin specialty item that elevates gourmet and specialty food assortments.',
    specifications: [
      { label: 'Container', value: 'Resealable spice tins' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Assorted Spice Blends' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–12 business days',
    inStock: true,
    featured: true,
    badge: 'Specialty',
  },

  // ---------------- Grocery & Non-Perishables ----------------
  {
    id: 'gold-medal-cotton-candy-cones',
    name: 'Gold Medal 300-Pack Cotton Candy Cones',
    sku: 'ETD-GROC-2001',
    category: 'Grocery & Non-Perishables',
    categoryId: 'grocery',
    price: 28.0,
    moq: 4,
    unit: 'case',
    image: '/images/products/goldmedal-cones.png',
    images: ['/images/products/goldmedal-cones.png'],
    shortDescription: 'Bulk 300-pack paper cotton candy cones for concessions and events.',
    description:
      'Gold Medal Cotton Candy Cones come in a bulk 300-pack, ideal for concession stands, fairs, events, and entertainment venues. A dependable high-volume consumable for foodservice and event supply buyers.',
    specifications: [
      { label: 'Pack Size', value: '300 cones' },
      { label: 'Packs per Case', value: '4' },
      { label: 'Material', value: 'Paper cones' },
      { label: 'Use', value: 'Cotton candy / concessions' },
      { label: 'Packaging', value: 'Bulk case' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'organic-pb-peanut-butter',
    name: 'Organic PB Peanut Butter',
    sku: 'ETD-GROC-2002',
    category: 'Grocery & Non-Perishables',
    categoryId: 'grocery',
    price: 45.0,
    moq: 12,
    unit: 'case',
    image: '/images/products/organic-pb.png',
    images: ['/images/products/organic-pb.png'],
    shortDescription: 'Organic peanut butter in retail jars for grocery and natural food channels.',
    description:
      'Organic PB Peanut Butter is made from simple, organic ingredients for a clean, creamy spread. A strong performer in grocery, natural, and specialty food channels, backed by reliable supply.',
    specifications: [
      { label: 'Jar Size', value: '16 oz' },
      { label: 'Jars per Case', value: '12' },
      { label: 'Type', value: 'Organic Peanut Butter' },
      { label: 'Packaging', value: 'Retail jars, case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },

  // ---------------- Health & Wellness ----------------
  {
    id: 'iqbar-chocolate-sea-salt',
    name: 'IQBAR Chocolate Sea Salt',
    sku: 'ETD-WELL-3001',
    category: 'Health & Wellness',
    categoryId: 'wellness',
    price: 24.0,
    moq: 12,
    unit: 'box',
    image: '/images/products/iqbar-chocolate.png',
    images: ['/images/products/iqbar-chocolate.png'],
    shortDescription: 'Plant-based protein bars in chocolate sea salt flavor, sold by the box.',
    description:
      'IQBAR Chocolate Sea Salt is a plant-based, low-sugar protein and brain-nutrient bar with rich chocolate flavor and a hint of sea salt. A strong seller for health, wellness, and convenience retailers.',
    specifications: [
      { label: 'Flavor', value: 'Chocolate Sea Salt' },
      { label: 'Bars per Box', value: '12' },
      { label: 'Type', value: 'Plant-Based Protein Bar' },
      { label: 'Packaging', value: 'Retail display box' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard ground shipping available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'New Arrival',
  },
  {
    id: 'iqbar-peanut-butter-chip',
    name: 'IQBAR Peanut Butter Chip',
    sku: 'ETD-WELL-3002',
    category: 'Health & Wellness',
    categoryId: 'wellness',
    price: 24.0,
    moq: 12,
    unit: 'box',
    image: '/images/products/iqbar-pb.png',
    images: ['/images/products/iqbar-pb.png'],
    shortDescription: 'Plant-based protein bars in peanut butter chip flavor, sold by the box.',
    description:
      'IQBAR Peanut Butter Chip pairs creamy peanut butter with chocolate chips in a plant-based, low-sugar protein bar. A dependable wellness snack for health-focused retailers and convenience channels.',
    specifications: [
      { label: 'Flavor', value: 'Peanut Butter Chip' },
      { label: 'Bars per Box', value: '12' },
      { label: 'Type', value: 'Plant-Based Protein Bar' },
      { label: 'Packaging', value: 'Retail display box' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard ground shipping available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'iqbar-lemon-blueberry',
    name: 'IQBAR Lemon Blueberry',
    sku: 'ETD-WELL-3003',
    category: 'Health & Wellness',
    categoryId: 'wellness',
    price: 24.0,
    moq: 12,
    unit: 'box',
    image: '/images/products/iqbar-lemon.png',
    images: ['/images/products/iqbar-lemon.png'],
    shortDescription: 'Plant-based protein bars in bright lemon blueberry flavor, sold by the box.',
    description:
      'IQBAR Lemon Blueberry offers a bright, fruit-forward take on the plant-based, low-sugar protein bar. A refreshing flavor option that rounds out any wellness snack assortment.',
    specifications: [
      { label: 'Flavor', value: 'Lemon Blueberry' },
      { label: 'Bars per Box', value: '12' },
      { label: 'Type', value: 'Plant-Based Protein Bar' },
      { label: 'Packaging', value: 'Retail display box' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard ground shipping available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'sky-and-sol-products',
    name: 'Sky & Sol Products',
    sku: 'ETD-WELL-3004',
    category: 'Health & Wellness',
    categoryId: 'wellness',
    price: 38.0,
    moq: 12,
    unit: 'case',
    image: '/images/products/skysol.png',
    images: ['/images/products/skysol.png'],
    shortDescription: 'Sky & Sol lifestyle and wellness beverages for modern retail assortments.',
    description:
      'Sky & Sol Products bring a clean, modern wellness offering to lifestyle and specialty retail. Sourced through trusted supplier relationships, this line adds contemporary appeal to health-focused assortments.',
    specifications: [
      { label: 'Format', value: 'Single-serve' },
      { label: 'Units per Case', value: '12' },
      { label: 'Category', value: 'Wellness / Lifestyle' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–12 business days',
    inStock: true,
    featured: false,
  },

  // ---------------- Home Goods ----------------
  {
    id: 'rubbermaid-commercial-storage',
    name: 'Rubbermaid Commercial Storage Solutions',
    sku: 'ETD-HOME-4001',
    category: 'Home Goods',
    categoryId: 'home',
    price: 95.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/rubbermaid-commercial.png',
    images: ['/images/products/rubbermaid-commercial.png'],
    shortDescription: 'Heavy-duty commercial storage totes and bins for business and retail buyers.',
    description:
      'Rubbermaid Commercial Storage Solutions offer durable, heavy-duty totes and bins built for demanding environments. A reliable home and business goods line for general merchandise and wholesale buyers.',
    specifications: [
      { label: 'Type', value: 'Commercial storage totes' },
      { label: 'Units per Case', value: '6' },
      { label: 'Material', value: 'Heavy-duty plastic' },
      { label: 'Use', value: 'Commercial / bulk storage' },
      { label: 'Packaging', value: 'Case pack' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–14 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'honeywell-air-purifier-filters',
    name: 'Honeywell Air Purifier Filters',
    sku: 'ETD-HOME-4002',
    category: 'Home Goods',
    categoryId: 'home',
    price: 60.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/honeywell-filters.png',
    images: ['/images/products/honeywell-filters.png'],
    shortDescription: 'Replacement HEPA air purifier filters for home and retail channels.',
    description:
      'Honeywell Air Purifier Filters are high-quality replacement HEPA filters that capture airborne particles for cleaner indoor air. A dependable, recurring-purchase home goods item for retail and wholesale buyers.',
    specifications: [
      { label: 'Type', value: 'HEPA replacement filters' },
      { label: 'Units per Case', value: '6' },
      { label: 'Compatibility', value: 'Home air purifiers' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Replacement', value: 'Periodic' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–14 business days',
    inStock: true,
    featured: true,
    badge: 'Popular',
  },
  {
    id: 'honeywell-home-safety-products',
    name: 'Honeywell Home Safety Products',
    sku: 'ETD-HOME-4003',
    category: 'Home Goods',
    categoryId: 'home',
    price: 85.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/honeywell-safety.png',
    images: ['/images/products/honeywell-safety.png'],
    shortDescription: 'Home safety devices including detectors and safety essentials for retail.',
    description:
      'Honeywell Home Safety Products include reliable detectors and safety essentials that help protect households. A trusted, high-demand home goods category for general merchandise and wholesale buyers.',
    specifications: [
      { label: 'Type', value: 'Home safety devices' },
      { label: 'Units per Case', value: '6' },
      { label: 'Use', value: 'Detection & home safety' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Category', value: 'Home Safety' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–14 business days',
    inStock: true,
    featured: false,
  },

  // ---------------- Kitchen & Dining ----------------
  {
    id: 'rubbermaid-food-storage-containers',
    name: 'Rubbermaid Food Storage Containers',
    sku: 'ETD-KTCH-5001',
    category: 'Kitchen & Dining',
    categoryId: 'kitchen',
    price: 42.0,
    moq: 12,
    unit: 'set',
    image: '/images/products/rubbermaid-food-storage.png',
    images: ['/images/products/rubbermaid-food-storage.png'],
    shortDescription: 'Nested food storage container sets with snap-lock lids for retail.',
    description:
      'Rubbermaid Food Storage Containers offer durable, leak-resistant sets with snap-lock lids for everyday kitchen use. A high-turn kitchen and dining staple for home stores and general merchandise retailers.',
    specifications: [
      { label: 'Set Contents', value: 'Assorted nested containers + lids' },
      { label: 'Sets per Case', value: '12' },
      { label: 'Material', value: 'BPA-free plastic' },
      { label: 'Dishwasher Safe', value: 'Yes' },
      { label: 'Packaging', value: 'Retail set' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 'cork-pops-wine-accessories',
    name: 'Cork Pops Wine Accessories',
    sku: 'ETD-KTCH-5002',
    category: 'Kitchen & Dining',
    categoryId: 'kitchen',
    price: 36.0,
    moq: 12,
    unit: 'case',
    image: '/images/products/corkpops-wine.png',
    images: ['/images/products/corkpops-wine.png'],
    shortDescription: 'Wine accessory sets including foil cutters, pourers, and drip rings.',
    description:
      'Cork Pops Wine Accessories bundle essential wine tools—foil cutters, pourers, and drip rings—into an attractive, giftable set. A strong impulse and gift-channel item for kitchen and dining retail.',
    specifications: [
      { label: 'Set Contents', value: 'Foil cutter, pourer, drip ring' },
      { label: 'Units per Case', value: '12' },
      { label: 'Material', value: 'Stainless steel' },
      { label: 'Use', value: 'Wine service' },
      { label: 'Packaging', value: 'Retail-ready case' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'cork-pops-bottle-openers',
    name: 'Cork Pops Bottle Openers',
    sku: 'ETD-KTCH-5003',
    category: 'Kitchen & Dining',
    categoryId: 'kitchen',
    price: 30.0,
    moq: 12,
    unit: 'case',
    image: '/images/products/corkpops-openers.png',
    images: ['/images/products/corkpops-openers.png'],
    shortDescription: 'Sleek wine bottle openers for kitchen, dining, and gift retail.',
    description:
      'Cork Pops Bottle Openers deliver quick, effortless cork removal with a sleek, modern design. A dependable impulse and gift-channel product for kitchen and dining retailers.',
    specifications: [
      { label: 'Type', value: 'Wine bottle opener' },
      { label: 'Units per Case', value: '12' },
      { label: 'Material', value: 'Chrome & composite' },
      { label: 'Use', value: 'Wine service' },
      { label: 'Packaging', value: 'Retail-ready case' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'Popular',
  },
]

// Featured brands and product lines carried through our sourcing network.
export const featuredBrands = [
  'Torani',
  'McCormick',
  'Old Bay',
  'Gold Medal',
  'IQBAR',
  'Rubbermaid',
  'Honeywell',
  'Cork Pops',
  'Zabs',
  'Sky & Sol',
  'Organic PB',
  'Spicewalla',
]

// Featured supplier relationships within our sourcing network.
export const featuredSuppliers = [
  'Torani',
  'McCormick',
  'Gold Medal',
  'IQBAR',
  'Rubbermaid',
  'Honeywell',
  'Spicewalla',
  'Cork Pops',
]

export const stats = [
  { value: '25+', label: 'Active SKUs' },
  { value: '12+', label: 'Supplier Relationships' },
  { value: '48', label: 'States Served' },
  { value: '10,000+', label: 'Orders Fulfilled' },
]
