export type Category = {
  id: string
  name: string
  description: string
  image: string
  count: number
}

export type Product = {
  id: string
  name: string
  sku: string
  category: string
  categoryId: string
  price: number
  moq: number
  unit: string
  image: string
  images: string[]
  shortDescription: string
  description: string
  specifications: { label: string; value: string }[]
  shipping: string
  leadTime: string
  inStock: boolean
  featured: boolean
  badge?: string
}

export const categories: Category[] = [
  {
    id: 'specialty',
    name: 'Specialty Foods',
    description: 'Gourmet syrups, seasonings, spice blends, and specialty condiments',
    image: '/images/category-specialty.png',
    count: 14,
  },
  {
    id: 'grocery',
    name: 'Grocery & Non-Perishables',
    description: 'Pantry staples, shelf-stable goods, and everyday grocery items',
    image: '/images/category-grocery.png',
    count: 1,
  },
  {
    id: 'wellness',
    name: 'Health & Wellness',
    description: 'Protein bars, functional foods, sunscreen, and wellness products',
    image: '/images/category-wellness.png',
    count: 5,
  },
  {
    id: 'home',
    name: 'Home Goods',
    description: 'Food storage, home safety, bedding, and household essentials',
    image: '/images/category-home.png',
    count: 3,
  },
  {
    id: 'kitchen',
    name: 'Kitchen & Dining',
    description: 'Food storage, wine accessories, and dining essentials',
    image: '/images/category-kitchen.png',
    count: 2,
  },
]

export const products: Product[] = [
  // ---------------- Specialty Foods ----------------
  {
    id: 'torani-vanilla-syrup',
    name: 'Torani Vanilla Syrup',
    sku: 'ETD-SPEC-1001',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 47.96,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-vanilla.jpg',
    images: ['/images/products/torani-vanilla.jpg'],
    shortDescription: 'Classic vanilla flavoring syrup for cafés, coffee shops, and foodservice, sold by the case.',
    description:
      'A café staple, Torani Vanilla Syrup delivers smooth, sweet vanilla flavor to lattes, cold brew, sodas, and desserts. A dependable high-turn item for coffee shops, restaurants, and foodservice buyers, sourced through trusted supplier relationships for consistent supply.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Price per Unit', value: '$11.99' },
      { label: 'Price per Case', value: '$47.96' },
      { label: 'Flavor', value: 'Vanilla' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 'torani-sugar-free-vanilla-syrup',
    name: 'Torani Sugar Free Vanilla Syrup',
    sku: 'ETD-SPEC-1002',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 48.5,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-sf-vanilla.png',
    images: ['/images/products/torani-sf-vanilla.png'],
    shortDescription: 'Sugar-free vanilla flavoring syrup for cafés and foodservice buyers.',
    description:
      'Torani Sugar Free Vanilla Syrup offers the same smooth vanilla flavor with zero sugar, sweetened for guests looking for lighter options. A strong complement to any café syrup lineup with reliable, consistent supply.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Price per Case', value: '$48.50' },
      { label: 'Flavor', value: 'Vanilla (Sugar Free)' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'torani-caramel-syrup',
    name: 'Torani Caramel Syrup',
    sku: 'ETD-SPEC-1003',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 48.5,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-caramel.png',
    images: ['/images/products/torani-caramel.png'],
    shortDescription: 'Rich caramel flavoring syrup for lattes, desserts, and specialty beverages.',
    description:
      'Torani Caramel Syrup brings buttery, rich caramel flavor to hot and iced beverages, desserts, and specialty drinks. A popular choice across coffee shops and foodservice, backed by dependable sourcing.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Price per Case', value: '$48.50' },
      { label: 'Flavor', value: 'Caramel' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'torani-hazelnut-syrup',
    name: 'Torani Hazelnut Syrup',
    sku: 'ETD-SPEC-1004',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 48.5,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-hazelnut.png',
    images: ['/images/products/torani-hazelnut.png'],
    shortDescription: 'Hazelnut flavoring syrup for coffee, cocoa, and specialty drinks.',
    description:
      'Torani Hazelnut Syrup adds a warm, toasted-nut sweetness that pairs perfectly with coffee and cocoa. A dependable menu builder for cafés and foodservice operators seeking consistent quality.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Price per Case', value: '$48.50' },
      { label: 'Flavor', value: 'Hazelnut' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'torani-french-vanilla-syrup',
    name: 'Torani French Vanilla Syrup',
    sku: 'ETD-SPEC-1005',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 48.5,
    moq: 4,
    unit: 'case',
    image: '/images/products/torani-french-vanilla.png',
    images: ['/images/products/torani-french-vanilla.png'],
    shortDescription: 'Creamy French vanilla syrup for lattes, cold brew, and desserts.',
    description:
      'Torani French Vanilla Syrup delivers a rich, custard-like vanilla flavor that rounds out any beverage program. A reliable, high-velocity flavor for coffee shops and foodservice buyers.',
    specifications: [
      { label: 'Bottle Size', value: '750ml' },
      { label: 'Bottles per Case', value: '4' },
      { label: 'Price per Case', value: '$48.50' },
      { label: 'Flavor', value: 'French Vanilla' },
      { label: 'Packaging', value: 'Glass bottles, retail case' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight and LTL options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'mccormick-curry-powder',
    name: 'McCormick Curry Powder 16 oz',
    sku: 'ETD-SPEC-1006',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-curry.png',
    images: ['/images/products/mccormick-curry.png'],
    shortDescription: 'Curry powder blend for grocery, specialty, and foodservice channels.',
    description:
      'McCormick Curry Powder is a balanced blend of warm spices that adds golden color and rich flavor to countless dishes. A dependable pantry seasoning for grocery retailers and kitchens alike.',
    specifications: [
      { label: 'Container', value: '16 oz' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Curry Powder Blend' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'mccormick-italian-seasoning',
    name: 'McCormick Italian Seasoning',
    sku: 'ETD-SPEC-1007',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-italian.png',
    images: ['/images/products/mccormick-italian.png'],
    shortDescription: 'Italian herb seasoning blend for retail and foodservice buyers.',
    description:
      'McCormick Italian Seasoning combines oregano, basil, thyme, and rosemary into a versatile, high-turn herb blend. A pantry essential across grocery and specialty food channels.',
    specifications: [
      { label: 'Container', value: 'Foodservice / retail size' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Italian Herb Blend' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 'mccormick-chili-powder',
    name: 'McCormick Dark Chili Powder 20 oz',
    sku: 'ETD-SPEC-1008',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-chili.png',
    images: ['/images/products/mccormick-chili.png'],
    shortDescription: 'Chili powder blend for grocery and foodservice channels.',
    description:
      'McCormick Dark Chili Powder delivers deep, warm flavor for chilis, sauces, rubs, and marinades. A dependable everyday seasoning with reliable supply for retailers and kitchens.',
    specifications: [
      { label: 'Container', value: '20 oz' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Dark Chili Powder Blend' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'mccormick-garlic-powder',
    name: 'McCormick Garlic Powder 36 oz',
    sku: 'ETD-SPEC-1009',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-garlic.png',
    images: ['/images/products/mccormick-garlic.png'],
    shortDescription: 'Garlic powder for everyday cooking, retail, and foodservice.',
    description:
      'McCormick Garlic Powder brings convenient, consistent garlic flavor to any dish. A top-selling pantry staple with dependable supply for grocery and foodservice buyers.',
    specifications: [
      { label: 'Container', value: '36 oz' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Garlic Powder' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'mccormick-ground-cinnamon',
    name: 'McCormick Ground Cinnamon 18 oz',
    sku: 'ETD-SPEC-1010',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 38.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/mccormick-cinnamon.png',
    images: ['/images/products/mccormick-cinnamon.png'],
    shortDescription: 'Ground cinnamon for baking, beverages, and everyday cooking.',
    description:
      'McCormick Ground Cinnamon adds warm, sweet spice to baked goods, beverages, and breakfast favorites. A reliable, high-turn baking staple for grocery and specialty retailers.',
    specifications: [
      { label: 'Container', value: '18 oz' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Ground Cinnamon' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'old-bay-seasoning',
    name: 'Old Bay Seasoning 24 oz',
    sku: 'ETD-SPEC-1011',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 42.0,
    moq: 6,
    unit: 'case',
    image: '/images/products/oldbay.png',
    images: ['/images/products/oldbay.png'],
    shortDescription: 'Classic seafood and all-purpose seasoning for retail and foodservice.',
    description:
      'Old Bay Seasoning is the iconic blend of herbs and spices loved on seafood, fries, snacks, and more. A recognizable, high-demand seasoning that performs across grocery and foodservice channels.',
    specifications: [
      { label: 'Container', value: '24 oz' },
      { label: 'Units per Case', value: '6' },
      { label: 'Type', value: 'Seafood Seasoning Blend' },
      { label: 'Packaging', value: 'Retail-ready case' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'Popular',
  },
  {
    id: 'spicewalla-honey-herb-rub',
    name: 'Spicewalla Honey and Herb Rub 3.8 oz',
    sku: 'ETD-SPEC-1012',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 14.49,
    moq: 6,
    unit: 'unit',
    image: '/images/products/spicewalla.png',
    images: ['/images/products/spicewalla.png'],
    shortDescription: 'Specialty spice product for gourmet grocery and retail buyers.',
    description:
      'Spicewalla Honey and Herb Rub is a fresh, small-batch blend packaged in a sleek resealable tin. A high-margin specialty item that elevates gourmet and specialty food assortments.',
    specifications: [
      { label: 'Container', value: '3.8 oz resealable tin' },
      { label: 'Type', value: 'Honey and Herb Rub' },
      { label: 'Packaging', value: 'Retail-ready tin' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–12 business days',
    inStock: true,
    featured: true,
    badge: 'Specialty',
  },
  {
    id: 'zabs-original-hot-sauce',
    name: "Zab's Original Hot Sauce",
    sku: 'ETD-SPEC-1013',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 16.99,
    moq: 12,
    unit: 'unit',
    image: '/images/products/zabs-original-hot-sauce.jpg',
    images: ['/images/products/zabs-original-hot-sauce.jpg'],
    shortDescription: 'Datil pepper hot sauce with a bright, balanced heat profile for specialty food and gourmet retail.',
    description:
      "Zab's Original Hot Sauce delivers a bright, balanced datil pepper heat crafted for specialty food and gourmet retail channels. A distinctive small-batch condiment that adds variety to any hot sauce set, sourced through trusted supplier relationships.",
    specifications: [
      { label: 'Bottle Size', value: '5 oz' },
      { label: 'Type', value: 'Datil Pepper Hot Sauce' },
      { label: 'Packaging', value: 'Glass bottle, retail' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–12 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'zabs-st-augustine-hot-sauce',
    name: "Zab's St. Augustine Style Hot Sauce",
    sku: 'ETD-SPEC-1014',
    category: 'Specialty Foods',
    categoryId: 'specialty',
    price: 16.99,
    moq: 12,
    unit: 'unit',
    image: '/images/products/zabs-st-augustine-hot-sauce.jpg',
    images: ['/images/products/zabs-st-augustine-hot-sauce.jpg'],
    shortDescription: 'Datil pepper hot sauce with a smooth, savory St. Augustine style flavor for specialty food buyers.',
    description:
      "Zab's St. Augustine Style Hot Sauce brings a smooth, savory datil pepper flavor inspired by Florida's oldest city. A distinctive small-batch condiment for specialty food and gourmet retail buyers.",
    specifications: [
      { label: 'Bottle Size', value: '5 oz' },
      { label: 'Type', value: 'Datil Pepper Hot Sauce' },
      { label: 'Packaging', value: 'Glass bottle, retail' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–12 business days',
    inStock: true,
    featured: false,
  },

  // ---------------- Grocery & Non-Perishables ----------------
  {
    id: 'gold-medal-cotton-candy-cones',
    name: 'Gold Medal GM3321 Plain Cotton Candy Cones (Pack of 300)',
    sku: 'ETD-GROC-2001',
    category: 'Grocery & Non-Perishables',
    categoryId: 'grocery',
    price: 28.0,
    moq: 4,
    unit: 'case',
    image: '/images/products/goldmedal-cones.png',
    images: ['/images/products/goldmedal-cones.png'],
    shortDescription: 'Bulk 300-pack paper cotton candy cones for concessions and events.',
    description:
      'Gold Medal GM3321 Cotton Candy Cones come in a bulk 300-pack, ideal for concession stands, fairs, events, and entertainment venues. A dependable high-volume consumable for foodservice and event supply buyers.',
    specifications: [
      { label: 'Pack Size', value: '300 cones' },
      { label: 'Packs per Case', value: '4' },
      { label: 'Material', value: 'Paper cones' },
      { label: 'Use', value: 'Cotton candy / concessions' },
      { label: 'Packaging', value: 'Bulk case' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },

  // ---------------- Health & Wellness ----------------
  {
    id: 'iqbar-chocolate-sea-salt',
    name: 'IQBAR Chocolate Sea Salt',
    sku: 'ETD-WELL-3001',
    category: 'Health & Wellness',
    categoryId: 'wellness',
    price: 24.0,
    moq: 12,
    unit: 'box',
    image: '/images/products/iqbar-chocolate.png',
    images: ['/images/products/iqbar-chocolate.png'],
    shortDescription: 'Plant-based protein bars in chocolate sea salt flavor, sold by the box.',
    description:
      'IQBAR Chocolate Sea Salt is a plant-based, low-sugar protein and brain-nutrient bar with rich chocolate flavor and a hint of sea salt. A strong seller for health, wellness, and convenience retailers.',
    specifications: [
      { label: 'Flavor', value: 'Chocolate Sea Salt' },
      { label: 'Bars per Box', value: '12' },
      { label: 'Type', value: 'Plant-Based Protein Bar' },
      { label: 'Packaging', value: 'Retail display box' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard ground shipping available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'New Arrival',
  },
  {
    id: 'iqbar-peanut-butter-chip',
    name: 'IQBAR Peanut Butter Chip',
    sku: 'ETD-WELL-3002',
    category: 'Health & Wellness',
    categoryId: 'wellness',
    price: 24.0,
    moq: 12,
    unit: 'box',
    image: '/images/products/iqbar-pb.png',
    images: ['/images/products/iqbar-pb.png'],
    shortDescription: 'Plant-based protein bars in peanut butter chip flavor, sold by the box.',
    description:
      'IQBAR Peanut Butter Chip pairs creamy peanut butter with chocolate chips in a plant-based, low-sugar protein bar. A dependable wellness snack for health-focused retailers and convenience channels.',
    specifications: [
      { label: 'Flavor', value: 'Peanut Butter Chip' },
      { label: 'Bars per Box', value: '12' },
      { label: 'Type', value: 'Plant-Based Protein Bar' },
      { label: 'Packaging', value: 'Retail display box' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard ground shipping available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'iqbar-lemon-blueberry',
    name: 'IQBAR Lemon Blueberry',
    sku: 'ETD-WELL-3003',
    category: 'Health & Wellness',
    categoryId: 'wellness',
    price: 24.0,
    moq: 12,
    unit: 'box',
    image: '/images/products/iqbar-lemon.png',
    images: ['/images/products/iqbar-lemon.png'],
    shortDescription: 'Plant-based protein bars in lemon blueberry flavor, sold by the box.',
    description:
      'IQBAR Lemon Blueberry offers a bright, fruit-forward take on the plant-based, low-sugar protein bar. A refreshing flavor option that rounds out any wellness snack assortment.',
    specifications: [
      { label: 'Flavor', value: 'Lemon Blueberry' },
      { label: 'Bars per Box', value: '12' },
      { label: 'Type', value: 'Plant-Based Protein Bar' },
      { label: 'Packaging', value: 'Retail display box' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard ground shipping available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'organic-pb-fit-powder',
    name: 'Organic PB Fit Peanut Butter Powder 30 oz',
    sku: 'ETD-WELL-3004',
    category: 'Health & Wellness',
    categoryId: 'wellness',
    price: 24.98,
    moq: 12,
    unit: 'unit',
    image: '/images/products/organic-pb-fit-powder.webp',
    images: ['/images/products/organic-pb-fit-powder.webp'],
    shortDescription: 'Peanut butter powder in a 30 oz size for health, wellness, grocery, and pantry-focused retail buyers.',
    description:
      'Organic PB Fit Peanut Butter Powder delivers the flavor of peanut butter with a fraction of the fat in a convenient 30 oz size. A strong performer in health, wellness, grocery, and pantry-focused retail, backed by reliable supply.',
    specifications: [
      { label: 'Size', value: '30 oz' },
      { label: 'Type', value: 'Peanut Butter Powder' },
      { label: 'Packaging', value: 'Retail jar' },
      { label: 'Shelf Stable', value: 'Yes' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'sky-sol-sunscreen',
    name: 'Sky & Sol Mineral Sunscreen SPF 50',
    sku: 'ETD-WELL-3005',
    category: 'Health & Wellness',
    categoryId: 'wellness',
    price: 35.95,
    moq: 12,
    unit: 'unit',
    image: '/images/products/sky-sol-sunscreen.jpg',
    images: ['/images/products/sky-sol-sunscreen.jpg'],
    shortDescription: 'Mineral face and body sunscreen made with tallow and zinc oxide for health, wellness, and personal care retail.',
    description:
      'Sky & Sol Mineral Sunscreen SPF 50 is a face and body sunscreen made with tallow and zinc oxide for clean, effective sun protection. A contemporary personal care item that adds modern appeal to health and wellness assortments.',
    specifications: [
      { label: 'SPF', value: 'SPF 50' },
      { label: 'Type', value: 'Mineral Sunscreen (Face & Body)' },
      { label: 'Key Ingredients', value: 'Tallow, Zinc Oxide' },
      { label: 'Packaging', value: 'Retail tube' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–12 business days',
    inStock: true,
    featured: false,
  },

  // ---------------- Home Goods ----------------
  {
    id: 'rubbermaid-commercial-6qt',
    name: 'Rubbermaid Commercial 6 Qt Food Storage Container',
    sku: 'ETD-HOME-4001',
    category: 'Home Goods',
    categoryId: 'home',
    price: 17.99,
    moq: 6,
    unit: 'unit',
    image: '/images/products/rubbermaid-commercial-6qt.jpg',
    images: ['/images/products/rubbermaid-commercial-6qt.jpg'],
    shortDescription: 'Clear square 6 quart food storage container for kitchen, meal prep, and commercial storage use.',
    description:
      'The Rubbermaid Commercial 6 Qt Food Storage Container is a clear, square, stackable container built for kitchen, meal prep, and commercial storage use. A dependable, high-turn home and business goods item for retail and wholesale buyers.',
    specifications: [
      { label: 'Capacity', value: '6 Quart' },
      { label: 'Shape', value: 'Clear square' },
      { label: 'Material', value: 'Durable commercial plastic' },
      { label: 'Use', value: 'Food storage / meal prep' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–14 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'honeywell-thermostat-guard',
    name: 'Honeywell Home CG512A1009 Thermostat Guard',
    sku: 'ETD-HOME-4002',
    category: 'Home Goods',
    categoryId: 'home',
    price: 32.9,
    moq: 6,
    unit: 'unit',
    image: '/images/products/honeywell-thermostat-guard.jpg',
    images: ['/images/products/honeywell-thermostat-guard.jpg'],
    shortDescription: 'Clear thermostat guard designed to protect wall thermostats in residential, commercial, and property-management settings.',
    description:
      'The Honeywell Home CG512A1009 Thermostat Guard is a clear, lockable cover that protects wall thermostats from tampering and damage. A trusted, high-demand item for residential, commercial, and property-management settings.',
    specifications: [
      { label: 'Model', value: 'CG512A1009' },
      { label: 'Type', value: 'Thermostat Guard' },
      { label: 'Finish', value: 'Clear' },
      { label: 'Use', value: 'Residential / commercial / property management' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–14 business days',
    inStock: true,
    featured: false,
  },
  {
    id: 'tempur-pedic-mattress-pad',
    name: 'Tempur-Pedic Cool Luxury Mattress Pad, Queen',
    sku: 'ETD-HOME-4003',
    category: 'Home Goods',
    categoryId: 'home',
    price: 179.98,
    moq: 4,
    unit: 'unit',
    image: '/images/products/tempur-pedic-mattress-pad.jpg',
    images: ['/images/products/tempur-pedic-mattress-pad.jpg'],
    shortDescription: 'Queen-size cooling luxury mattress pad for bedding, home goods, and household comfort assortments.',
    description:
      'The Tempur-Pedic Cool Luxury Mattress Pad in Queen size adds cooling comfort and a premium feel to any bed. A high-value bedding item for home goods and household comfort assortments.',
    specifications: [
      { label: 'Size', value: 'Queen' },
      { label: 'Type', value: 'Cooling Mattress Pad' },
      { label: 'Brand', value: 'Tempur-Pedic' },
      { label: 'Use', value: 'Bedding / home comfort' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '7–14 business days',
    inStock: true,
    featured: true,
    badge: 'Popular',
  },

  // ---------------- Kitchen & Dining ----------------
  {
    id: 'rubbermaid-brilliance-16cup',
    name: 'Rubbermaid Brilliance 16-Cup Airtight Food Storage Container',
    sku: 'ETD-KTCH-5001',
    category: 'Kitchen & Dining',
    categoryId: 'kitchen',
    price: 21.48,
    moq: 6,
    unit: 'unit',
    image: '/images/products/rubbermaid-brilliance-16cup.jpg',
    images: ['/images/products/rubbermaid-brilliance-16cup.jpg'],
    shortDescription: 'Airtight clear food storage container with lid for pantry organization, flour, sugar, and dry goods.',
    description:
      'The Rubbermaid Brilliance 16-Cup Airtight Food Storage Container keeps flour, sugar, and dry goods fresh with a leak-proof, airtight lid and crystal-clear design. A high-turn kitchen and dining staple for home stores and general merchandise retailers.',
    specifications: [
      { label: 'Capacity', value: '16 Cup' },
      { label: 'Seal', value: 'Airtight, leak-proof lid' },
      { label: 'Material', value: 'BPA-free Tritan plastic' },
      { label: 'Use', value: 'Pantry organization / dry goods' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 'cork-pops-refill-cartridges',
    name: 'Cork Pops Wine Bottle Opener Refill Cartridges, 2-Pack',
    sku: 'ETD-KTCH-5002',
    category: 'Kitchen & Dining',
    categoryId: 'kitchen',
    price: 36.99,
    moq: 12,
    unit: 'unit',
    image: '/images/products/cork-pops-refill-cartridges.jpg',
    images: ['/images/products/cork-pops-refill-cartridges.jpg'],
    shortDescription: 'Low-pressure refill cartridges compatible with Cork Pops wine bottle openers.',
    description:
      'Cork Pops Wine Bottle Opener Refill Cartridges come in a convenient 2-pack of low-pressure cartridges compatible with Cork Pops openers. A dependable recurring-purchase accessory for kitchen, dining, and gift retail.',
    specifications: [
      { label: 'Pack', value: '2-Pack' },
      { label: 'Type', value: 'Refill Cartridges' },
      { label: 'Compatibility', value: 'Cork Pops wine bottle openers' },
      { label: 'Use', value: 'Wine service' },
    ],
    shipping: 'Ships from Woodstock, NY. Standard freight options available.',
    leadTime: '5–10 business days',
    inStock: true,
    featured: false,
  },
]

// Featured brands and product lines carried through our sourcing network.
export const featuredBrands = [
  'Torani',
  'McCormick',
  'Old Bay',
  'Gold Medal',
  'IQBAR',
  'Rubbermaid',
  'Honeywell',
  'Cork Pops',
  "Zab's",
  'Sky & Sol',
  'Tempur-Pedic',
  'Spicewalla',
]

// Featured supplier relationships within our sourcing network.
export const featuredSuppliers = [
  'Torani',
  'McCormick',
  'Gold Medal',
  'IQBAR',
  'Rubbermaid',
  'Honeywell',
  'Spicewalla',
  'Cork Pops',
]

export const stats = [
  { value: '25+', label: 'Active SKUs' },
  { value: '12+', label: 'Supplier Relationships' },
  { value: '48', label: 'States Served' },
  { value: '10,000+', label: 'Orders Fulfilled' },
]
